      REAL*8         BRNAME                                             M29.  10
      COMMON  /COM44/  BCARS(30), CCARS(30),  DCARS(30), FBE(20)        M14. 120
      COMMON  /COM44/  BRNAME(40)                                       M31.  58
      COMMON  /COM44/  FBED(20), FKE(20), FKED(20), PI, PICON, SQRT2    M14. 121
      COMMON  /COM44/  VALU1, VALU2, VALU3, VALU4, VALU5, VALU6, VALU7  M14. 122
      COMMON  /COM44/  VALU8, VALU9, VALU10, VALU11, VALU12, VALU13     M14. 123
      COMMON  /COM44/  CORCHK, AAA1, AAA2                               M15.  22
      COMMON  /COM44/  LL0, LL1, LL2, LL3, LL5, LL6, LL7, LL8, LL9, LL10M14. 125
      COMMON  /COM44/  LPHASE, LPHPL1, LPHD2, LGDBD, JPRALT,NFREQ       M30.  66
