      COMMON/COM47/  BIN(20), BKN(20), CIMAG1, CREAL1, CZERO, YPO       M35. 163
C     END OF COMPLEX VARIABLES                                          M29.  14
      COMMON/COM47/  ALF1, ALF2, DEP1, DEP2, E0, E2P, RADP(3)           M35. 164
      COMMON/COM47/  ALPI, BP1, BP2, ES1, ES2, ROP, USP                 M35. 165
      COMMON/COM47/  HYUD2, HYUD3, HYUD4, HTOJ2, HTOJ3, FZERO           M35. 166
      COMMON/COM47/  HTOJ4,PAI,ROE,SPDLGT,U0,U2P                        M35. 167
      COMMON/COM47/  VALUE1, VALUE2, VALUE3, VALUE4, VALUE5,VALU14      M35. 168
C     END OF REAL VARIABLES                                             M29.  18
      COMMON/COM47/  IEARTH,ITYPEC,NCCT,NCC,NPC,IZFLAG,IYFLAG,NPC2      M35. 169
      COMMON/COM47/  NP2,LOGSIX,KMODE,IPRS47,NPAIS,NCROS,NUMAKI,NPP     M35. 170
      COMMON/COM47/  IPRINT                                             VAX.   3
C     END OF INTEGER VARIABLES                                          M29.  19
      COMPLEX*16  BIN, BKN, CIMAG1, CREAL1, CZERO, YPO                  M35. 171
