      REAL*8       PL                                                   M20.  36
      COMMON /COM45/ PL(91)                                             M20.  37
      COMMON /COM45/ F, W, COLD, XPAN, CONV5, RATIO, PI2, SLL, SPDLT    M20.  38
      COMMON /COM45/ TT, TSTRT, TRETRD, TSTEP, FFIN, SHIFTR, SHIFTI     M20.  39
      COMMON / COM45 / D, X(3), DPLU, DMIN, ICTRL, I1                   M20.  40
      COMMON / COM45 / IWORK,NPH,NPH2,NPHPI2,N22,NPHSQ,NTRI             M16. 158
      COMMON / COM45 /  ISS,NFR,NFR1,IX, KREQAB                         M39.  46
